<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>lui</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../backends/winui3/AppManifest.cs" Link="AppManifest.cs" />
    <Compile Include="../packaging/PackageBuilder.cs" Link="PackageBuilder.cs" />
  </ItemGroup>
</Project>
